# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 382e0b01abcc036d865280ef0856366c0b1aedb191040a87840ca65ac59d1a92e2f3a2b501b5b4e313ab6d29c29dc7c8638e59fdc839da1044d76613e3ffeaff

test:
  secret_key_base: df63e14aa8e6abde2852bfe7610e44ff422b5da27152020abb288ed64c8df642f4aa072b9a974176440b39c68ff9a061f2b33da5747072b1617937b43fcaf6df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
